//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderZone
    {
        public int Id { get; set; }
        public string Logo { get; set; }
        public string Slogan { get; set; }
        public string FooterText { get; set; }
        public string FacebookAddress { get; set; }
        public string TwitterAddress { get; set; }
        public string GPlusAddress { get; set; }
        public string InstagramAddress { get; set; }
    }
}
